export const genres = [
  { id: "action", title: "Ação" },
  { id: "adventure", title: "Aventura" },
  { id: "animation", title: "Animação" },
  { id: "comedy", title: "Comédia" },
  { id: "crime", title: "Crime" },
  { id: "documentary", title: "Documentário" },
  { id: "drama", title: "Drama" },
  { id: "family", title: "Família" },
  { id: "fantasy", title: "Fantasia" },
  { id: "history", title: "História" },
  { id: "horror", title: "Terror" },
  { id: "music", title: "Música" },
  { id: "mystery", title: "Mistério" },
  { id: "romance", title: "Romance" },
  { id: "science-fiction", title: "Ficção Científica" },
  { id: "thriller", title: "Suspense" },
  { id: "war", title: "Guerra" },
  { id: "western", title: "Faroeste" },
];

export const genresTitles = {
  action: "Ação",
  adventure: "Aventura",
  animation: "Animação",
  comedy: "Comédia",
  crime: "Crime",
  documentary: "Documentário",
  drama: "Drama",
  family: "Família",
  fantasy: "Fantasia",
  history: "História",
  horror: "Terror",
  music: "Música",
  mystery: "Mistério",
  romance: "Romance",
  "science-fiction": "Ficção Científica",
  thriller: "Suspense",
  war: "Guerra",
  western: "Faroeste",
} as const;
