export const languages = [
  { id: "pt", title: "Português" },
  { id: "en", title: "Inglês" },
  { id: "es", title: "Espanhol" },
  { id: "fr", title: "Francês" },
  { id: "it", title: "Italiano" },
  { id: "de", title: "Alemão" },
  { id: "ja", title: "Japonês" },
  { id: "ko", title: "Coreano" },
  { id: "zh", title: "Chinês" },
  { id: "ru", title: "Russo" },
  { id: "hi", title: "Hindi" },
  { id: "ar", title: "Árabe" },
  { id: "tr", title: "Turco" },
  { id: "sv", title: "Sueco" },
  { id: "nl", title: "Holandês" },
];

export const languagesTitles = {
  pt: "Português",
  en: "Inglês",
  es: "Espanhol",
  fr: "Francês",
  it: "Italiano",
  de: "Alemão",
  ja: "Japonês",
  ko: "Coreano",
  zh: "Chinês",
  ru: "Russo",
  hi: "Hindi",
  ar: "Árabe",
  tr: "Turco",
  sv: "Sueco",
  nl: "Holandês",
} as const;
