services:
  postgres:
    image: postgres:17-alpine
    container_name: cubos_postgres
    restart: always
    environment:
      POSTGRES_USER: cubos
      POSTGRES_PASSWORD: cubos-pass
      POSTGRES_DB: cubos_movie
    ports:
      - '5432:5432'
    volumes:
      - cubos_db_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: cubos_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: cubos
      MINIO_ROOT_PASSWORD: cubos-pass
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Console
    volumes:
      - cubos_minio_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cubos_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  cubos_db_data:
  cubos_minio_data:
